spring:
  application:
    name: micro-user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: 123456
server:
  port: 8000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false