# Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
spring:
  application:
    name: micro-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 9000
