# Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
spring:
  application:
    name: micro-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://micro-user-service
          predicates:
            - Path=/micro-user-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://micro-order-service
          predicates:
            - Path=/micro-order-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8090
